import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, Literal, Optional, Union

import numpy as np
import pandas as pd
from numpy.typing import NDArray
from pyedflib import EdfReader
from torch_ecg.cfg import CFG
from torch_ecg.databases.base import DataBaseInfo, PSGDataBaseMixin, _DataBase
from torch_ecg.utils.misc import add_docstring

from cfg import BaseCfg
from const import PROJECT_DIR, SLEEP_STAGE_MAPPING
from helper_code import load_rename_rules, standardize_channel_names_rename_only

__all__ = [
    "CINC2026",
]


_CINC2026_INFO = DataBaseInfo(
    title="Screening for Cognitive Impairment During Sleep Studies: The George B. Moody PhysioNet Challenge 2026",
    about="""
    1. The George B. Moody PhysioNet Challenge 2026 invites teams to develop algorithmic approaches for using polysomnography (PSG) to predict future diagnoses of cognitive impairment (MCI, Alzheimer’s disease, or dementia).
    2. The data are from the Human Sleep Project (HSP) database [3]_, including clinical PSG data from five different U.S. institutions (BIDMC, Emory, Kaiser, MGB, and Stanford).
    3. The official-phase training set contains **1 103 records** (small set, 214 GiB) or **~6 600 records** (large set, 1.2 TiB) from three sites: S0001, I0002, I0006.  It includes synchronized physiological signals in EDF format.  The signals are heterogeneous across sites but generally include Electroencephalography (EEG), Electrooculography (EOG), Electromyography (EMG), Electrocardiography (ECG), Respiratory effort sensors, and Airflow sensors.
    4. Two types of annotations are provided:
        - Algorithmic Annotations (CAISR): Generated by the Complete AI Sleep Report framework [4]_. Available for training, validation, and test sets. Includes sleep stages (W, N1, N2, N3, REM), arousals, respiratory events, and limb movements.
        - Human Annotations: Gold-standard clinical annotations from sleep experts following AASM guidelines. Only available for the training sets.
    5. The primary label is **"Cognitive_Impairment"** (Binary).  For the official phase a patient is **positive** if they have at least two qualifying ICD-9/ICD-10 codes for cognitive impairment whose **first diagnosis falls between 1 and 6 years** after the PSG (the unofficial phase used a 3–7 year window).  The training-set labels are pre-computed in ``demographics.csv``; the ``ICD_codes_CI.csv`` file and ``create_labels.py`` script document the label-generation logic.
    6. The "demographics.csv" file contains metadata such as Age, Sex, Race, BMI, and the binary target label.
    """,
    usage=[
        "Cognitive impairment screening",
        "Dementia prediction",
        "Sleep stage classification",
        "Sleep disorder detection (Apnea, Arousal, PLM)",
        "Biomarker discovery from PSG",
    ],
    note="""
    The challenge utilizes a hidden test set for final evaluation. The metric is AUROC on the specific cognitive impairment definition.
    """,
    issues="""
    1. Signal Heterogeneity: The availability, sampling rates, and filter settings of physiological channels vary significantly between different recording sites and even within the same dataset.
       - S0001 (572 training records): bipolar EEG derivations (e.g. ``f3-m2``), uniform 200 Hz for EEG/EOG/EMG channels, slow channels (SpO2, airflow) at 25 Hz.
       - I0002 (54 training records): same bipolar derivation convention as S0001, but EEG sampling rate is inconsistent within the site (200 Hz or 500 Hz per record).
       - I0006 (154 training records): unipolar EEG electrodes (``f3``, ``c3``, ``m1``, ``m2``, etc.), up to five different sampling rates within a single recording (10/20/50/100/200 Hz), and ``thermistor`` instead of ``airflow`` for oral airflow.
    2. Class Imbalance shift: The training set is artificially balanced (approx. 50% positive), whereas the validation and test sets reflect real-world prevalence (5-15% positive).
    3. Temporal Shift: Sleep study dates were shifted by randomly chosen integers between ±365 days.
    4. Age Capping: Patient ages above 89 are replaced with a single category of "90".
    5. Incomplete CAISR Annotations: 14 out of 780 training records (1.8%) are missing CAISR annotation EDF files. All 14 stem from recordings that contain no EEG, EOG, or EMG channels (only respiratory and ECG signals are present), which makes sleep staging — and therefore the CAISR pipeline — impossible.
    6. CAISR Probability Scale Bug: The five ``caisr_prob_*`` channels (N3, N2, N1, REM, Wake posterior probabilities) are stored with an EDF ``physical_max`` header of 9 instead of 1. As a result, pyedflib scales the raw integer codes into the range [0, 9] rather than [0, 1].
    7. CAISR EDF Channel Layout: Each CAISR annotation EDF contains exactly 11 signals in a fixed order:

       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       | idx | Signal name         | fs (Hz) | Range     | Description                                                |
       +=====+=====================+=========+===========+============================================================+
       |  0  | arousal_caisr       |   2.0   | {0, 1}    | Arousal binary label, 0.5 s resolution (60 samples/epoch)  |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  1  | caisr_prob_no-ar    |   2.0   | [0, 1]    | Probability of no-arousal, 0.5 s resolution                |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  2  | caisr_prob_arous    |   2.0   | [0, 1]    | Probability of arousal, 0.5 s resolution                   |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  3  | limb_caisr          |   1.0   | {0,1,2}   | Limb movement: 0=none, 1=isolated, 2=periodic (30/epoch)   |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  4  | resp_caisr          |   1.0   | {0..4}    | Resp. event: 0=none,1=OA,2=CA,3=MA,4=HY (30/epoch)        |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  5  | stage_caisr         | 1/30    | {1,2,3,4,5,9} | Sleep stage per epoch: 1=N3,2=N2,3=N1,4=REM,5=W,9=Unavail |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  6  | caisr_prob_n3       | 1/30    | [0, 9]*   | N3 posterior probability (EDF scale bug; raw ÷ 9 → [0,1]) |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  7  | caisr_prob_n2       | 1/30    | [0, 9]*   | N2 posterior probability                                   |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  8  | caisr_prob_n1       | 1/30    | [0, 9]*   | N1 posterior probability                                   |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       |  9  | caisr_prob_r        | 1/30    | [0, 9]*   | REM posterior probability                                  |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+
       | 10  | caisr_prob_w        | 1/30    | [0, 9]*   | Wake posterior probability                                 |
       +-----+---------------------+---------+-----------+------------------------------------------------------------+

       (*) EDF physical_max=9 scale bug — see issue 6.
    """,
    references=[
        "https://moody-challenge.physionet.org/2026/",
        "https://bdsp.io/content/hsp/",
        "https://pubmed.ncbi.nlm.nih.gov/40554678/",  # CAISR paper
        "https://github.com/physionetchallenges/python-example-2026",
    ],
    doi=[
        "10.60508/qjbv-hg78",  # Human Sleep Project
        "10.1093/sleep/zsaf134",  # CAISR paper
        "10.5664/jcsm.9476",  # Sleep essential to health
        "10.3389/fneur.2015.00224",  # Role of Sleep in Neurocognitive Disorders
    ],
)


@add_docstring(_CINC2026_INFO.format_database_docstring(), mode="prepend")
class CINC2026(_DataBase, PSGDataBaseMixin):
    """

    Parameters
    ----------
    db_dir : `path-like`, optional
        Storage path of the database.
        If not specified, data will be fetched from Physionet.
    working_dir : `path-like`, optional
        Working directory, to store intermediate files and log files.
    verbose : int, default 1
        Level of logging verbosity.
    kwargs : dict, optional
        Auxilliary key word arguments.

    """

    __name__ = "CINC2026"

    __sleep_stage_mapping__ = SLEEP_STAGE_MAPPING.copy()

    def __init__(
        self,
        db_dir: Optional[Union[str, bytes, os.PathLike]] = None,
        working_dir: Optional[Union[str, bytes, os.PathLike]] = None,
        verbose: int = 1,
        **kwargs: Any,
    ) -> None:
        super().__init__(
            db_name="CINC2026",
            db_dir=db_dir,
            working_dir=working_dir,
            verbose=verbose,
            **kwargs,
        )
        self.__config = CFG(BaseCfg.copy())
        self.__config.update(kwargs)

        self._df_records = pd.DataFrame()
        self._all_records = []
        self._channel_rename_rules = load_rename_rules(os.path.join(PROJECT_DIR, "channel_table.csv"))

        if self.db_dir is not None:
            self.db_dir = Path(self.db_dir)
            self._ls_rec()

    def _ls_rec(self) -> None:
        """Find all records in the database directory and store them in a dataframe.

        Two data layouts are supported:

        **Standard (nested) layout** — db_dir is the dataset root containing
        one or more named partition sub-folders::

            db_dir/
            ├── training_set_small/        (or training_set_large/  or training_set/ for unofficial)
            │   ├── demographics.csv
            │   ├── ICD_codes_CI.csv
            │   ├── algorithmic_annotations/
            │   ├── human_annotations/
            │   └── physiological_data/
            └── supplementary_set/
                └── ...

        **Flat layout** — db_dir itself is a single partition directory (as
        passed by the PhysioNet challenge evaluator at inference / training time)::

            db_dir/
            ├── demographics.csv
            ├── algorithmic_annotations/
            ├── human_annotations/
            └── physiological_data/

        In the flat layout the partition is assumed to be ``"training_set"``
        during training and ``"test_set"`` at inference.  :meth:`_resolve_db_dir`
        is **not** relied upon for path correction here; instead the check is
        performed locally so the reader always produces a valid ``_df_records``.
        """
        self._df_records = pd.DataFrame()
        dfs = []

        def _build_partition_df(demo_path: Path, data_root: Path, part_name: str) -> pd.DataFrame:
            """Read demographics.csv and append path columns for one partition."""
            df = pd.read_csv(demo_path)
            df["partition"] = part_name

            physio_dir = data_root / "physiological_data"
            algo_dir = data_root / "algorithmic_annotations"
            human_dir = data_root / "human_annotations"

            def get_paths(row):
                base_name = f"{row['BidsFolder']}_ses-{row['SessionID']}"
                site_id = row["SiteID"]
                physio_path = physio_dir / site_id / f"{base_name}.edf"
                algo_path = algo_dir / site_id / f"{base_name}_caisr_annotations.edf"
                human_path_str = None
                if human_dir.exists():
                    hp = human_dir / site_id / f"{base_name}_expert_annotations.edf"
                    if hp.exists():
                        human_path_str = str(hp)
                return pd.Series(
                    [str(physio_path), str(algo_path), human_path_str],
                    index=["path", "algo_ann_path", "human_ann_path"],
                )

            paths = df.apply(get_paths, axis=1)
            return pd.concat([df, paths], axis=1)

        # ── Standard (nested) layout ──────────────────────────────────────────
        # Official phase uses "training_set_small" / "training_set_large";
        # unofficial phase used "training_set".  All three are recognised.
        for part in ["training_set", "training_set_small", "training_set_large", "supplementary_set"]:
            demo_path = self.db_dir / part / "demographics.csv"
            if demo_path.exists():
                dfs.append(_build_partition_df(demo_path, self.db_dir / part, part))

        # ── Flat layout fallback ──────────────────────────────────────────────
        # If no nested partitions were found, check whether db_dir itself
        # contains demographics.csv (challenge evaluator flat layout).
        if not dfs:
            flat_demo = self.db_dir / "demographics.csv"
            if flat_demo.exists():
                dfs.append(_build_partition_df(flat_demo, self.db_dir, "training_set"))

        if dfs:
            self._df_records = pd.concat(dfs, ignore_index=True)
            self._df_records.set_index("BidsFolder", inplace=True)
            self._all_records = self._df_records.index.tolist()
        else:
            self._all_records = []

    def load_data(
        self,
        rec: Union[str, int],
        **kwargs: Any,
    ) -> Dict[str, Union[Dict[str, np.ndarray], Dict[str, float]]]:
        """
        Load physiological data for a record.

        Parameters
        ----------
        rec : str or int
            The record identifier (BidsFolder).

        Returns
        -------
        dict
            {'signals': {label: array}, 'fs': {label: fs}}
        """
        if isinstance(rec, int):
            rec = self._all_records[rec]

        if rec not in self._df_records.index:
            raise ValueError(f"Record {rec} not found.")

        row = self._df_records.loc[rec]
        path = str(row["path"])

        if not os.path.exists(path):
            raise FileNotFoundError(f"Physiological data file not found: {path}")

        try:
            reader = EdfReader(path)
            signals = {}
            fs_dict = {}
            labels = reader.getSignalLabels()

            # Apply channel renaming if rename_rules exist
            rename_map = {}
            if self._channel_rename_rules:
                rename_map, _ = standardize_channel_names_rename_only(labels, self._channel_rename_rules)

            for i, label in enumerate(labels):
                # If we have a rename map, use it to standardize the label
                # otherwise just lowercase and strip
                if label in rename_map:
                    clean_label = rename_map[label]
                else:
                    clean_label = label.lower().strip()

                # If standardization resulted in duplicates (e.g. multiple channels mapping to same std name),
                # the later one overwrites the former.
                # In helper_code.py, they have logic to drop duplicates, but here we just read everything.
                # If we want to be strict, we should follow helper_code's logic of keeping only one.
                # For now, let's just load it.

                signals[clean_label] = reader.readSignal(i)
                fs_dict[clean_label] = reader.getSampleFrequency(i)

            reader._close()
            return {"signals": signals, "fs": fs_dict}

        except Exception as e:
            if self.verbose >= 1:
                print(f"Error loading EDF {path}: {e}")
            return {}

    def load_ann(
        self,
        rec: Union[str, int],
        ann_type: Literal["algorithmic", "human", "both"] = "both",
        **kwargs: Any,
    ) -> Dict[str, Any]:
        """
        Load annotations for a record.

        Parameters
        ----------
        rec : str or int
            The record identifier.
        ann_type : {"algorithmic", "human", "both"}, default "both"
            "algorithmic" (CAISR) or "human" annotations.
            "both" will load both types if available.

        Returns
        -------
        dict
            Dictionary containing annotation signals/events.
        """
        if isinstance(rec, int):
            rec = self._all_records[rec]

        row = self._df_records.loc[rec]

        if ann_type == "human":
            path = str(row.get("human_ann_path"))
        elif ann_type == "algorithmic":
            path = str(row.get("algo_ann_path"))
        elif ann_type == "both":
            return self.load_ann(rec, ann_type="algorithmic") | self.load_ann(rec, ann_type="human")
        else:
            raise ValueError(f"ann_type must be 'algorithmic', 'human', or 'both', got {ann_type}")

        if not path or pd.isna(path) or not os.path.exists(path):
            if self.verbose >= 1:
                print(f"Annotation file not found for {rec}, type {ann_type}")
            return {}

        try:
            reader = EdfReader(path)
            annotations = {}
            labels = reader.getSignalLabels()

            # Read signals (e.g. stage_caisr, arousal_caisr)
            for i, label in enumerate(labels):
                clean_label = label.lower().strip()
                annotations[clean_label] = reader.readSignal(i)

            # Read EDF+ annotations if present
            try:
                ann_tuple = reader.readAnnotations()
                if ann_tuple[0].size > 0:
                    annotations["events"] = ann_tuple
            except Exception:
                pass

            reader._close()
            return annotations

        except Exception as e:
            if self.verbose >= 1:
                print(f"Error loading annotation {path}: {e}")
            return {}

    def safe_edf_file_operation(
        self,
        operation: Literal["open", "close"] = "close",
        full_file_path: Optional[Union[str, bytes, os.PathLike]] = None,
    ) -> None:
        """Safe IO operation for edf file.

        Parameters
        ----------
        operation : {"open", "close"}, default "close"
            Operation name.
        full_file_path : `path-like`, optional
            Path of the file which contains the data.
            If is None, default path will be used.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If the operation is not supported.

        """
        if operation == "open":
            if getattr(self, "file_opened", None) is not None:
                self.file_opened._close()  # type: ignore
            self.file_opened = EdfReader(str(full_file_path))
        elif operation == "close":
            if getattr(self, "file_opened", None) is not None:
                self.file_opened._close()  # type: ignore
                self.file_opened = None
        else:
            raise ValueError("Illegal operation")

    def plot_hypnogram(  # type: ignore
        self,
        mask: NDArray,
        granularity: int = 30,
        **kwargs,
    ) -> tuple:
        """Hypnogram visualization.

        Parameters
        ----------
        mask : numpy.ndarray
            Sleep stage mask.
        granularity : int, default 30
            Granularity of the sleep stage mask to be plotted,
            with units in seconds.
        kwargs : dict, optional
            Additional keyword arguments passed to :meth:`matplotlib.pyplot.plot`.

        Returns
        -------
        fig : matplotlib.figure.Figure
            Figure object.
        ax : matplotlib.axes.Axes
            Axes object.

        Example
        -------
        ```python
        dr = CINC2026(db_dir="/path/to/db")
        anns = dr.load_ann(rec=0, ann_type="both")
        fig_human, ax_human = dr.plot_hypnogram(anns["stage_expert"])  # human annotations
        fig_algo, ax_algo = dr.plot_hypnogram(anns["stage_caisr"])  # algorithmic annotations
        ```

        """
        if kwargs.pop("class_map", None) is not None:
            self.logger.warning("CINC2026 has a fixed sleep stage mapping, the provided class_map will be ignored.")  # type: ignore
        return super().plot_hypnogram(mask, granularity, class_map=self.__sleep_stage_mapping__, **kwargs)

    def compare_annotations(
        self,
        recs: Optional[Union[str, int, list]] = None,
        verbose: bool = False,
    ) -> Dict[str, Any]:
        """Compare CAISR (algorithmic) vs human annotations for one or more records.

        Computes agreement statistics for four annotation types:
        - **stage**: Sleep stage per 30 s epoch. Cohen's kappa (linear-weighted),
          overall accuracy, and per-class recall.
        - **arousal**: Binary event flag per 0.5 s sample. Cohen's kappa,
          sensitivity (recall for event=1), specificity, and F1.
        - **resp**: Respiratory events per 2 s sample. Binary (any event vs none)
          because CAISR and expert use incompatible codebooks.
          Cohen's kappa and F1 (event=positive class).
        - **limb**: Limb movement events per 2 s sample. Binary comparison
          (CAISR merges isolated=1 and periodic=2 into one class; expert uses 0/1).
          Cohen's kappa and F1.

        Parameters
        ----------
        recs : str, int, list, or None
            Record(s) to analyse. An integer is treated as an index into
            ``self._all_records``.  ``None`` processes all training records
            that have human annotations.
        verbose : bool
            If True, print per-record progress.

        Returns
        -------
        dict with keys:
            ``"per_record"``  – DataFrame with one row per record.
            ``"aggregate"``   – dict of aggregate statistics across records.
            ``"n_records"``   – number of records successfully processed.

        Examples
        --------
        >>> dr = CINC2026("/Data1/wenh06/physionetchallenge2026data")
        >>> result = dr.compare_annotations()
        >>> print(result["aggregate"])
        """
        from sklearn.metrics import (
            cohen_kappa_score,
            f1_score,
        )

        stage_names = {1: "N3", 2: "N2", 3: "N1", 4: "REM", 5: "W", 9: "Unknown"}

        # ------------------------------------------------------------------
        # Resolve record list
        # ------------------------------------------------------------------
        if recs is None:
            # All records with human annotations (training_set only)
            mask = self._df_records.get("human_ann_path", pd.Series(dtype=str)).notna()
            recs_list = self._df_records.index[mask].tolist()
        elif isinstance(recs, (str, int)):
            recs_list = [recs]
        else:
            recs_list = list(recs)

        rows = []
        skipped = 0

        for rec in recs_list:
            if isinstance(rec, int):
                rec = self._all_records[rec]

            if verbose:
                print(f"Processing {rec}…")

            ann_algo = self.load_ann(rec, ann_type="algorithmic")
            ann_human = self.load_ann(rec, ann_type="human")

            if not ann_algo or not ann_human:
                skipped += 1
                continue

            row: Dict[str, Any] = {"record": rec}

            # ---- sleep staging ----------------------------------------
            s_algo = ann_algo.get("stage_caisr")
            s_human = ann_human.get("stage_expert")
            if s_algo is not None and s_human is not None:
                n = min(len(s_algo), len(s_human))
                a = np.round(s_algo[:n]).astype(int)
                h = np.round(s_human[:n]).astype(int)
                # drop epochs where either side is "Unavailable" (9)
                valid = (a != 9) & (h != 9)
                a_v, h_v = a[valid], h[valid]
                try:
                    kappa = cohen_kappa_score(h_v, a_v, weights="linear")
                except Exception:
                    kappa = float("nan")
                acc = np.mean(a_v == h_v)
                row["stage_kappa"] = kappa
                row["stage_acc"] = acc
                row["stage_n_epochs"] = n
                # per-class recall
                all_labels = sorted(set(np.concatenate([a_v, h_v])))
                for lbl in all_labels:
                    mask_h = h_v == lbl
                    if mask_h.sum() > 0:
                        row[f"stage_recall_{stage_names.get(lbl, lbl)}"] = np.mean(a_v[mask_h] == lbl)
                    else:
                        row[f"stage_recall_{stage_names.get(lbl, lbl)}"] = float("nan")

            # ---- arousal -----------------------------------------------
            ar_algo = ann_algo.get("arousal_caisr")
            ar_human = ann_human.get("arousal_expert")
            if ar_algo is not None and ar_human is not None:
                n = min(len(ar_algo), len(ar_human))
                a = (np.round(ar_algo[:n]) > 0).astype(int)
                h = (np.round(ar_human[:n]) > 0).astype(int)
                try:
                    kappa = cohen_kappa_score(h, a)
                except Exception:
                    kappa = float("nan")
                # sensitivity = recall for class 1; specificity = recall for class 0
                pos_mask = h == 1
                neg_mask = h == 0
                sens = np.mean(a[pos_mask] == 1) if pos_mask.sum() > 0 else float("nan")
                spec = np.mean(a[neg_mask] == 0) if neg_mask.sum() > 0 else float("nan")
                f1 = f1_score(h, a, zero_division=0)
                row["arousal_kappa"] = kappa
                row["arousal_sensitivity"] = sens
                row["arousal_specificity"] = spec
                row["arousal_f1"] = f1
                row["arousal_n_samples"] = n

            # ---- respiratory events ------------------------------------
            re_algo = ann_algo.get("resp_caisr")
            re_human = ann_human.get("resp_expert")
            if re_algo is not None and re_human is not None:
                n = min(len(re_algo), len(re_human))
                # Binary: any event (>0) vs none (0)
                a = (np.round(re_algo[:n]) > 0).astype(int)
                h = (np.round(re_human[:n]) > 0).astype(int)
                try:
                    kappa = cohen_kappa_score(h, a)
                except Exception:
                    kappa = float("nan")
                f1 = f1_score(h, a, zero_division=0)
                pos_mask = h == 1
                neg_mask = h == 0
                sens = np.mean(a[pos_mask] == 1) if pos_mask.sum() > 0 else float("nan")
                spec = np.mean(a[neg_mask] == 0) if neg_mask.sum() > 0 else float("nan")
                row["resp_kappa"] = kappa
                row["resp_f1"] = f1
                row["resp_sensitivity"] = sens
                row["resp_specificity"] = spec
                row["resp_n_samples"] = n

            # ---- limb movements ----------------------------------------
            lm_algo = ann_algo.get("limb_caisr")
            lm_human = ann_human.get("limb_expert")
            if lm_algo is not None and lm_human is not None:
                n = min(len(lm_algo), len(lm_human))
                # CAISR: 0=none, 1=isolated, 2=periodic → binary
                a = (np.round(lm_algo[:n]) > 0).astype(int)
                h = (np.round(lm_human[:n]) > 0).astype(int)
                try:
                    kappa = cohen_kappa_score(h, a)
                except Exception:
                    kappa = float("nan")
                f1 = f1_score(h, a, zero_division=0)
                pos_mask = h == 1
                neg_mask = h == 0
                sens = np.mean(a[pos_mask] == 1) if pos_mask.sum() > 0 else float("nan")
                spec = np.mean(a[neg_mask] == 0) if neg_mask.sum() > 0 else float("nan")
                row["limb_kappa"] = kappa
                row["limb_f1"] = f1
                row["limb_sensitivity"] = sens
                row["limb_specificity"] = spec
                row["limb_n_samples"] = n

            rows.append(row)

        if not rows:
            return {"per_record": pd.DataFrame(), "aggregate": {}, "n_records": 0}

        per_record = pd.DataFrame(rows).set_index("record")

        # ------------------------------------------------------------------
        # Aggregate: nanmean across records for each metric column
        # ------------------------------------------------------------------
        numeric_cols = per_record.select_dtypes(include=[np.number]).columns
        agg = {col: float(np.nanmean(per_record[col].values)) for col in numeric_cols}
        agg["n_records"] = len(per_record)
        agg["n_skipped"] = skipped

        if verbose:
            print(f"\nProcessed {len(per_record)} records ({skipped} skipped).")
            for k, v in agg.items():
                if isinstance(v, float):
                    print(f"  {k:<30s}: {v:.4f}")
                else:
                    print(f"  {k:<30s}: {v}")

        return {"per_record": per_record, "aggregate": agg, "n_records": len(per_record)}

    @property
    def url(self) -> Dict[str, str]:  # type: ignore
        return {
            "pycurl": "https://www.kaggle.com/api/v1/datasets/download/physionet/physionetchallenge2026data",
            "kagglehub": "physionet/physionetchallenge2026data",
            "mlcroissant": "https://www.kaggle.com/datasets/physionet/physionetchallenge2026data/croissant/download",
        }

    def download(self) -> None:
        """Download the database from Kaggle.

        The dataset is large (~100GB), use with caution.
        The function will try to use pycurl, then kagglehub, and
        finally mlcroissant to download the data. If none of these
        libraries are available, it will raise an ImportError.
        """
        try:
            import pycurl
        except ImportError:
            pycurl = None
        try:
            import kagglehub
        except ImportError:
            kagglehub = None
        try:
            import mlcroissant as mlc
        except ImportError:
            mlc = None

        # priority: pycurl > kagglehub > mlcroissant
        if pycurl is not None:
            self.logger.info("Downloading dataset using pycurl with resume support...")  # type: ignore
            output_path = self.db_dir / "physionetchallenge2026data.zip"
            download_with_resume_using_pycurl(self.url["pycurl"], str(output_path))
        elif kagglehub is not None:
            self.logger.info("Downloading dataset using kagglehub...")  # type: ignore
            path = kagglehub.dataset_download(
                "physionet/physionetchallenge2026data",
                output_dir=str(self.db_dir),
            )
            self.logger.info(f"Dataset downloaded to {path}")  # type: ignore
        elif mlc is not None:
            self.logger.info("Downloading dataset using mlcroissant...")  # type: ignore
            croissant_dataset = mlc.Dataset(self.url["mlcroissant"])
            # Check what record sets are in the dataset
            record_sets = croissant_dataset.metadata.record_sets
            self.logger.info(f"Totally {len(record_sets)} record sets in the dataset")  # type: ignore
        else:
            raise ImportError("No suitable library found for downloading. Please install pycurl, kagglehub, or mlcroissant.")

    @property
    def database_info(self) -> DataBaseInfo:
        return _CINC2026_INFO


def download_with_resume_using_pycurl(url: str, output_path: str, retries: int = 3) -> None:
    try:
        import pycurl
    except ImportError:
        raise ImportError("pycurl is required for this download method.")

    output_path = Path(output_path)  # type: ignore
    temp_file = output_path

    existing_size = temp_file.stat().st_size if temp_file.exists() else 0

    for attempt in range(retries):
        try:
            with open(temp_file, "ab") as f:
                c = pycurl.Curl()

                c.setopt(pycurl.URL, url)
                c.setopt(pycurl.WRITEDATA, f)
                c.setopt(pycurl.FOLLOWLOCATION, True)  # -L
                c.setopt(pycurl.NOPROGRESS, False)

                if existing_size > 0:
                    c.setopt(pycurl.RESUME_FROM_LARGE, existing_size)

                def progress(total, downloaded, upload_total, uploaded):
                    if total > 0:
                        percent = downloaded / total * 100
                        bar_len = 40
                        filled = int(bar_len * downloaded // total)
                        bar = "=" * filled + "-" * (bar_len - filled)
                        sys.stdout.write(f"\r[{bar}] {percent:6.2f}% " f"{downloaded/1024/1024:.1f}/{total/1024/1024:.1f} MB")
                        sys.stdout.flush()

                c.setopt(pycurl.XFERINFOFUNCTION, progress)

                c.perform()
                c.close()

            print("\nDownload completed.")
            return

        except pycurl.error as e:
            print(f"\nError: {e}, retrying ({attempt+1}/{retries})...")
            time.sleep(2)

    raise RuntimeError("Download failed after retries")
